spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASS}
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: validate
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB
    mvc:
        contentnegotiation:
            favor-parameter: true
            media-types.pdf: application/pdf
            media-types.json: application/json

logging:
   level:
        org:
            hibernate:
                SQL: debug 

server: #IMPORTANTE PARA PODER CONECTARSE DESDE HEROKU
    port: ${PORT}