spring:
    datasource:
        url: jdbc:mysql://localhost/amps_db?serverTimezone=America/Argentina/Ushuaia
        username: admin
        password: 2744mfuhR
        # url: jdbc:mysql://megasolution.com.ar/amps_db_prueba?serverTimezone=America/Argentina/Ushuaia
        # username: mfuhr
        # password: 2744mfuhR
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        # show-sql: true
        # properties:
        #     hibernate:
        #         format_sql: true
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB
    mvc:
        contentnegotiation:
            favor-parameter: true
            media-types.pdf: application/pdf
            
            

logging:
   level:
        org:
            hibernate:
                SQL: debug

jwt:
    secret: secret
    expiration: 36000