spring:
    datasource:
        url: jdbc:mysql://us-cdbr-east-03.cleardb.com/heroku_31977c4c268cada?reconnect=true
        username: b12f934281b05a
        password: e75bfbf6
        # url: jdbc:mysql://localhost/amps_db?serverTimezone=America/Argentina/Ushuaia
        # username: admin
        # password: 2744mfuhR
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: validate
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB
    mvc:
        contentnegotiation:
            favor-parameter: true
            media-types.pdf: application/pdf
            media-types.json: application/json

logging:
   level:
        org:
            hibernate:
                SQL: debug 

server: #IMPORTANTE PARA PODER CONECTARSE DESDE HEROKU
    port: ${PORT:8080}